### ISSUE TITLE
Calling a third party library from within LX Studio

### ISSUE THREAD

**Issue by finominal** [heronarts/LXStudio#1]
I am planning on using LX Studo to drive a project that includes hardware that monitors an array of proximity sensors.  (It's effectively a touch sensitive wall) 

I have created a library to communicate with my hardware, and return updated data when called. 

I am currently expecting to do the following:

- Add the library to the sketch.
- Within LX's lifecycle, call the library to do work, and call the library to get data. 
- Take action within an LX Pattern based on the state of the data. 

Assuming this is the right way to go about it: What is an appropriate place within LX to add the library, and where in the LX lifecycle should I call it periodically to get refreshed data? 

Cheers, 
Fin.

**Comment by mcslee** [comment]
Hey Fin - there's an easy way to do this using the LXLoopTask interface:
http://lx.studio/api/heronarts/lx/LXLoopTask.html

This interface has a loop(double deltaMs) method which is invoked on every loop of the engine.

You can add one of these to the engine runtime by using the method lx.engine.addLoopTask():
http://lx.studio/api/heronarts/lx/LXEngine.html#addLoopTask-heronarts.lx.LXLoopTask-

Put whatever you like inside your loop task to have it do work and retrieve any data that it has generated.

You are of course also free to invoke external libraries from patterns or effects, but I think the more general high-level library behavior you're asking for is what the top-level LXLoopTask is for.

If the library needs some initialization you can just do that in your setup() method, or in the initialize() callback.
