### ISSUE TITLE
onInactive() isn't called when a pattern is deleted from a list.

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#10]
Say I have a list of FORM patterns in some channel. If a pattern is currently being rendered, and then it is deleted using the delete key on the keyboard, another pattern will take its place. However, the pattern that was just deleted won't have its onInactive() method called.

**Comment by mcslee** [comment]
Nice catch.
https://github.com/heronarts/LX/commit/361d9558c8dc00ab01653c270ef1caf301ce2b6a

New release is cut on all the repos.
