### ISSUE TITLE
Request: Make Java source available

### ISSUE THREAD

**Issue by drichelson** [heronarts/LXStudio#12]
Would it be possible to make the source code of https://github.com/heronarts/LXStudio/blob/master/LXStudio/code/LXStudio.jar available? I'm trying to use IntelliJ instead of the Processing IDE. I can run LXStudio, but having the source code would help me figure out the best ways to structure the code including registering patterns, etc.

**Comment by mcslee** [comment]
Hey Dan - the source for the LX Studio application is closed for a few reasons. I prefer to just add hooks and APIs for people to extend as necessary. Shoot me an email at mcslee@gmail.com to let me know more about what you're working on? I'm curious what you're up to with the software, can grant read-access if need be.

FYI pattern-registration can go in your initialize() callback, and can look like this:
https://github.com/heronarts/P3LX/blob/master/src/heronarts/p3lx/P3LX.java#L114

Also FYI the Javadocs for LXStudio should be up here exposing what the public APIs are for hooks/integrations where need be: http://lx.studio/api/
