### ISSUE TITLE
Request for version numbers for each release

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#3]
I would love to attach version numbers to these releases because I'm using Maven for dependency management and, so far, I've been using 1.0.0 as the version number. Would it be possible to tag both this and whichever branch of the LX project it's based on with some incrementing semver.org-compatible version number?

**Comment by mcslee** [comment]
Yes, excellent call. And thank you for flagging this, it had been in the back of my mind to get a proper versioning scheme going for a while now.

I will try to stick to semver conventions as best as possible, but I still consider this API somewhat young/flexible and can't promise that there won't be the occasional non-backwards-compatible change (without a major version number increase). But I generally try to keep those to very easy-to-update things (like minor naming changes, find/replace situations, or just deprecating something that shouldn't be used anymore).

Totally happy to take feedback on that as we go though, and let me know if it's ever causing problems. I'm going to finish up a few fixes/cleanups I'm in the middle of, and I will then get a 1.0.0 tag out on all the repos.

**Comment by mcslee** [comment]
Okay cool - in that case I suppose I'll quite arbitrarily start with 0.1.0 and we'll go from there.

**Comment by ssilverman** [comment]
According to the semver spec, it allows pre-release versions to be tagged as such. eg. appending "-alpha" and such.

**Comment by mcslee** [comment]
I'm curious for your take, as a user of the software, whether alpha is appropriate. I don't really feel the the software is alpha anymore (many years of usage and lots of projects at this point) - but it lives in a weird place of sort of being "software mainly for a rapid-development hacking process."

Alpha to me feels like it communicates "unproven, untested" - whereas the right thing to communicate with LX is probably more like "this is still a fast-moving project that gets updated and responds to how people are using it fairly quickly."

But I'm obviously heavily biased by my own view and history with it, so I'm curious to get an outside take on how it feels to use it and what kind of naming might communicate the right thing.

**Comment by ssilverman** [comment]
If the API is changing in a major way, then unless it's labelled "-alpha" or "-beta" or "-gamma" or something, then according to semver, the major version needs to change. But that isn't really a problem in and of itself. For example, many projects out there use simple incrementing, or hack in the build date somehow. I'm personally not averse to projects that change their major version often, so, in my opinion, that shouldn't be a mental block to updating the API frequently.

**Comment by mcslee** [comment]
FYI per other comment, I've just added these. 
https://github.com/heronarts/LXStudio/releases/tag/0.1.0-alpha
https://github.com/heronarts/LX/releases/tag/0.1.0-alpha
https://github.com/heronarts/P3LX/releases/tag/0.1.0-alpha

The releases contain relevant packaged JARs. I can continue to cut these on a semi-regular basis from now on (or on demand, as you need them).

**Comment by ssilverman** [comment]
May I suggest, if you're going to use a 0.x release, that alpha isn't really necessary? It's more of a personal preference, but will there ever be a 0.1.0 non-alpha release?

**Comment by mcslee** [comment]
Yeah, agreed it's superfluous. Will drop the alpha from here on out...

**Comment by ssilverman** [comment]
Thank you very much for versioning these builds! :)

**Comment by ssilverman** [comment]
May I also suggest adding the version to the README.md file? This way, if I have some directory without knowing which zip it came from, I know which build it is. Additionally, some sort of version() static method in the main LXStudio class would be nice.
