### ISSUE TITLE
CompoundParameter is force set to the wrong value after initialization

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#4]
I have a pattern where I create a new `CompoundParameter` as a field declaration:
`private final CompoundParameter speedKnob = new CompoundParameter("Speed", 0.5, 0.0, 1.0);`

As far as I understand, this creates a parameter with initial value 0.5 and range 0.0-1.0.

I've been trying the following using all sorts of different orderings, but in the constructor: I add the parameter, add a listener to the parameter, and set the value on the parameter (some value that isn't 0.5 and isn't 1.0).

By the time my pattern sees the `onActive()`, the value of the parameter has been set to 1.0. This is unexpected.

(Side question: Is it better to use `CompoundParameter` or `BoundedParameter` for a knob in the UI?)

**Comment by mcslee** [comment]
I am not able to reproduce this. Do you have a minimal test case that reproduces this behavior? Is there possible a project file loading that is overwriting the value?

I just wrote the following test case, when I run it on my system, the printed value is 0.75, as expected (what I have set it to in the constructor).

Is it possible that the value being set is outside of the bounds for some reason? It would be clamped to 1.0 if it was greater than 1.0 for some reason.

public static class TestCompoundParameter extends LXPattern {
  
  private final CompoundParameter speedKnob = new CompoundParameter("Speed", 0.5, 0.0, 1.0);

  public TestCompoundParameter(LX lx) {
    super(lx);
    addParameter("speed", speedKnob);
    speedKnob.setValue(0.75);
  }
  
  public void onActive() {
    println(speedKnob.getValue());
  }
  
  public void run(double deltaMs) {
  }
}

> (Side question: Is it better to use CompoundParameter or BoundedParameter for a knob in the UI?)

To this question - a CompoundParameter is able to receive modulation from other parameters or modulators, like an LFO. A BoundedParameter is not eligible to receive modulation. You can use either one - I generally use CompoundParameter by default on the assumption that most things should be able to receive modulation.

**Comment by mcslee** [comment]
Another hack you might try - subclass your CompoundParameter that's having this issue as follows:

```
private final CompoundParameter speedKnob = new CompoundParameter("Speed", 0.5, 0.0, 1.0) {
  @Override
  protected double updateValue(double value) {
    // Figure out if there is a rogue setValue call, causing the value to update?
    new Exception().printStackTrace();
    return super.updateValue(double);
  }
};
```

**Comment by ssilverman** [comment]
OOoooh... It was the project file. I keep forgetting about those and that they affect things.

I just deleted the line from the project file, but to help manage this in case it's set to a bad or undesired value, I've added a boolean latch that's set on the first onActive() call.
