### ISSUE TITLE
((LXStudio-IDE)) java: package processing.core does not exist

### ISSUE THREAD

**Issue by nargetdev** [heronarts/LXStudio#5]
## Setup
From a clean clone.  Have tried Ubuntu and Mac OS X

Runs fine on both platforms on checkout of tag `0.4.1`

**Comment by nargetdev** [comment]
Able to get them in by explicitly specifying system paths in `pom.xml`

```
		<dependency>
			<groupId>org.processing</groupId>
			<artifactId>core</artifactId>
			<version>4.0b8</version>
<!--			<scope>provided</scope>-->
			<scope>system</scope>
			<systemPath>/Users/myuser/LXStudio-IDE/lib/processing-4.0b8/core-4.0b8.jar</systemPath>
		</dependency>
```

**Comment by mcslee** [comment]
This should be solvable by running `mvn validate` once, as described in the README section on configuring runtime:
https://github.com/heronarts/LXStudio-IDE#configure-your-runtime

That will install the Processing dependencies to your local maven repository. Should only need to be done once upfront.

**Comment by nargetdev** [comment]
I just saw that bit.

I also had to do a couple other odd things to get it working.

On Ubuntu (but not mac OS) the Java compiler version was preset to "1.5" rather than 17 which is deep in the settings..

<img width="967" alt="image" src="https://user-images.githubusercontent.com/6596924/199386766-ddf91335-477e-4a6b-aca0-e5e52f64e493.png">

Note, on Ubuntu...
I also had to symlink the lib up to `natives` folder at the root??

```
# at content root /path/to/LXStudio-IDE
mkdir -p ./natives
ln -sf $(pwd)/lib/processing-4.0.1/linux-amd64 natives
```


Anyways I'm running now but for whatever reason it took a lot of hacking.

**Comment by mcslee** [comment]
Ah, interesting, not sure about defaulting to 1.5. I usually use Eclipse so haven't seen that, possible that not all the IntelliJ settings are stored in the stock LXStudio-IDE project.

As for the natives link, it depends how you're passing the `-Djava.library.path` argument and where the `java` command is being executed from. Those two things need to line up properly, looks in your case maybe it's being passed as `-Dnatives` and running from your root folder.

I have a future version of all this stuff that I'm hoping to get out in the coming months which will turn all of this into a standalone app without all the IDE config and building pain. Stay tuned for that... in the meantime glad you got this sorted.
