### ISSUE TITLE
UIItemList listener for item changes would be useful

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#8]
This way, I can track if a selection has changed.

**Comment by mcslee** [comment]
I can add this - but curious which list you are using this on. If it is a list that you have constructed yourself, then the items all have methods which can be overridden to be notified when this happens:

http://lx.studio/api/heronarts/p3lx/ui/component/UIItemList.Item.html

Note the onFocus() method.

Can definitely see how it might still be nice to just have a global listener though.

**Comment by mcslee** [comment]
https://github.com/heronarts/P3LX/commit/398a679aed57754e6e4d10d72212f87226a5011f

**Comment by ssilverman** [comment]
Ah, I didn't know there was a UIItemList.Item.onFocus() method. With my past UI experience, I've never used any form of "element on-focus"; it's always a "list changed to here". I didn't even think of looking at the Item docs. Thank you for these changes.
